### ISSUE TITLE
Docker ignoring Environment variable

### ISSUE THREAD

**Issue by Raventhicc** [krateng/maloja#168]
```
maloja-maloja-1 | Various external services can be used to display images. If not enough of them are set up, only local images will be used.
maloja-maloja-1 |       Currently not using a Last.fm API Key for image display.
maloja-maloja-1 |       Currently not using a Spotify API ID for image display.
maloja-maloja-1 |       Currently not using a Spotify API Secret for image display.
maloja-maloja-1 |       Currently not using a TheAudioDB API Key for image display.
```
My Compose:
```yml
services:
  maloja:
    image: krateng/maloja:latest
    ports:
    - 42010:42010
    environment:
    - MALOJA_LASTFM_API_KEY=0000000000000000000000000000
    - MALOJA_LASTFM_API_SECRET=0000000000000000000000000000
    - MALOJA_SPOTIFY_API_ID=0000000000000000000000000000
    - MALOJA_SPOTIFY_API_SECRET=0000000000000000000000000000
    volumes:
    - docker/maloja/config:/etc/maloja
    - docker/maloja/data:/var/lib/maloja
    - docker/maloja/logs:/var/log/maloja
    restart: unless-stopped
```
