### ISSUE TITLE
[Solved] Can't scrobble Navidrome with Maloja

### ISSUE THREAD

**Issue by janaxhell** [krateng/maloja#213]
I have just deployed Maloja on my docker server where Navidrome lives. I have added my last.fm and spotify API keys, created a reverse proxied domain and added Maloja Scrobbler extension to my Vivaldi browser (for Windows). On the same browser I have Web Scrobbler extension. When I play any song from Navidrome, Web Scrobbler shows a popup telling it's scrobbling and I can see last.fm receiving the info. Majola on the other hand doesn't. I have set my majola URL+API in the extension in the format of https://my.domain.com, which shows them as green (= it's ok), but nothing happens.
What am I missing?

**Comment by krateng** [comment]
Does the Maloja scrobbler show a little 1 when the navidrome tab is open? You might have to reload the page after setting up the scrobbler. Also, it relies on URL to detect pages, so I believe if your server doesn't have the string 'navidrome' in its address, it will not detect it.

By the way, Web Scrobbler should also work with Maloja, and Navidrome itself can scrobble to Maloja directly without a browser extension.

**Comment by janaxhell** [comment]
Ahh, no, my Navidrome URL does not have "navidrome" word... Web Scrobbler acts weird: I have entered my plain Majola URL and a custom API key created for it, but it seems to get confused: the other Accounts for last.fm, Listenbrainz and Libre.fm bring me to the relative sites when I click Profile. Majola Profile bounces me to Web Scrobbler itself..

**Comment by ZackBoe** [comment]
For what it's worth, Web Scrobbler recently had what looks like a decently large rewrite. I've not yet been able to get it working with Maloja via Listenbrainz nor the native Maloja integration. I did some (late night and probably poor) debugging and didn't see it even attempt any network requests towards my Maloja server.

**Comment by janaxhell** [comment]
Ah, ok, so Web Scrobbler can't be used at this time. At least I can exclude that.

**Comment by janaxhell** [comment]
Any hint?
My Maloja compose looks like this:
```
version: '3.3'
services:
    maloja:
        image: krateng/maloja
        environment:
            - PUID=998
            - PGID=100
            - MALOJA_DATA_DIRECTORY=/mljdata
            - MALOJA_FORCE_PASSWORD=XXXXXXXX
        ports:
            - '42010:42010'
        volumes:
            - '/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Maloja:/mljdata'
```
and my Navidrome like this
```
version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: 998:100 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 0
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: "/music"
      ND_PLAYLISTSPATH: "lidarr/playlists"
      # ND_IMAGECACHESIZE: "100MB"
      ND_SPOTIFY_ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      ND_SPOTIFY_SECRET: XXXXXXXXXXXXXXXXXXXXXXXXXX
      ND_SUBSONICARTISTPARTICIPATIONS: true
      ND_LISTENBRAINZ_BASEURL: http://192.168.1.94:42010/apis/listenbrainz

      
    volumes:
      - "/srv/dev-disk-by-uuid-5b67514d-485e-4306-873e-b1cbb54ccf99/Config/Navidrome:/data"
      - "/srv/dev-disk-by-uuid-2628F1C228F19153/data/media/unmapped:/music/unmapped"
      - "/srv/dev-disk-by-uuid-2628F1C228F19153/data/media/music:/music/lidarr"
```
