### ISSUE TITLE
Cannot import last.fm scrobble history

### ISSUE THREAD

**Issue by jtd5048** [krateng/maloja#359]
I started with a compose file that calls for the image stored in Dockerhub:
```
maloja:
        image: krateng/maloja
        container_name: maloja
        restart: unless-stopped
        environment:
            - MALOJA_DATA_DIRECTORY=/mljdata
            - PUID=1000
            - PGID=1000
        ports:
            - 42010:42010
        volumes:
            - ./maloja/data:/mljdata
```

and then stopped container and used the import instructions to get into the container shell: `docker run -it --entrypoint sh -v $PWD/maloja/data:/mljdata -e MALOJA_DATA_DIRECTORY=/mljdata -e PUID=1000 -e PGID=1000 krateng/maloja`
and attempted `maloja import recenttrack-xyz.json`, exported from ghan64 site. this returns: `File could not be identified as a valid import source`

I then noticed that the dockerhub image is 5 months old and the change for ghan's site looks like it's a week old

so I cloned the repo and built the image myself using `docker build .`

when I shell into this container, the command `maloja import xyz.json` is not recognized: `sh: maloja: not found`

so I am stuck on importing my listening history. Dockerhub seems to be too old and building the image locally also does not work correctly. I've exhausted my technical understanding at this point. What am I doing wrong? Help would be much appreciated
